version: "3.8"

services:
  mongo:
    image: mongo:8.2.2
    container_name: mongo
    # restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mocktool
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    command: ["mongod", "--bind_ip_all"]
    networks:
        - mock
  redis:
    image: redis:7-alpine
    ports:
        - "6379:6379"
    networks:
        - mock

volumes:
  mongo_data:

networks:
    mock:
        driver: bridge